/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Fiscal Period]
      ,[Account Name]
      ,[Opportunity Name]
      ,[Account Executive]
      ,[Bid Lead]
      ,[Pre-Bid Meeting]
      ,[Bid Due Date]
      ,[Close Date]
      ,[Contract Type]
      ,[Amount]
      ,[Next Step]
      ,[Description]
      ,[Estimated Project Start Date]
      ,[Estimated Project End Date]
      ,[Contract Classification]
      ,[CY Revenue Est ]
      ,[Gross Margin % (As-Bid)]
      ,[Productive Revenue per Man-hour (As-Bid)]
      ,[# of Crews Needed]
      ,[Total Man-Hours (As-Bid)]
      ,[Project State]
      ,[Created Date]
      ,[Age]
      ,[Fiscal Year]
      ,[Opportunity Owner]
      ,[Opportunity Winner]
      ,[Disposition Reason]
      ,[Disposition Comments]
      ,[Winning Amount]
      ,[% High]
      ,[Probability (%)]
      ,[Opportunity ID]
      ,[Stage]
      ,[Scope]
  FROM [dbo].[DimOpportunity]